version: "3.8"

services:
  mysql8:
    image: mysql:8.0
    restart: always
    command:
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
    environment:
      MYSQL_ROOT_PASSWORD: testci
      TZ: Asia/Shanghai
    volumes:
      - ./volume/mysql/conf:/etc/mysql/conf.d
      - ./volume/mysql/data:/var/lib/mysql
      - ./volume/mysql/logs:/var/log/mysql
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  redis:
    image: 'bitnami/redis:7.2'
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=testci
    ports:
      - '6379:6379'

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      TZ: Asia/Shanghai
    ports:
      - "2181:2181"

  kafka:
    image: 'bitnami/kafka:3.6.0'
    restart: always
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181  # Kafka连接Zookeeper
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENER_NAME_EXTERNAL=EXTERNAL
      - KAFKA_CFG_LISTENER_PORT_EXTERNAL=9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_CFG_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LISTENER_PORT=9092
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_CREATE_TOPICS=webook_binlog:3:1
      - TZ=Asia/Shanghai
    depends_on:
      - zookeeper

