version: "3.8"

services:
  mysql8:
    image: mysql:8.0
    restart: always
    command:
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
    environment:
      MYSQL_ROOT_PASSWORD: testci
      TZ: Asia/Shanghai
    volumes:
      - ./volume/mysql/conf:/etc/mysql/conf.d
      - ./volume/mysql/data:/var/lib/mysql
      - ./volume/mysql/logs:/var/log/mysql
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  redis:
    image: 'bitnami/redis:7.2'
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=testci
    ports:
      - '6379:6379'

  kafka:
    image: bitnami/kafka:3.6.1
    environment:
      - KAFKA_KRAFT_MODE=true       # 启用 KRaft 模式
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_LISTENER_PORT=9092
      - KAFKA_BROKER_ID=1           # 设置 Broker ID
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false  # 禁用 Confluent 的指标收集（如果不需要）
      - KAFKA_LOG_RETENTION_HOURS=168  # 设置日志保留时间，单位为小时（默认7天）
      - KAFKA_CREATE_TOPICS=foo:1:1,bar:3:3  # 启动时自动创建主题 foo（1分区）和 bar（3分区）
      - TZ=Asia/Shanghai
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data  # 持久化 Kafka 数据