name: Go Test with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 检查代码版本
      - name: Checkout code
        uses: actions/checkout@v2
      # 安装go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.3

      # 检查是否能够编译
      - name: Install dependencies
        run: |
          go mod tidy
          go build .

      # 启动docker-compose
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose -f docker-compose.yaml up -d
          sleep 120 # 等待容器启动 2分钟

      - name: Run tests
        run: |
          go test -v ./...

      - name: Shut down Docker Compose
        run: |
          docker-compose -f docker-compose.yaml down
